server:
  port: 8765

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: quiz-service
          uri: lb://QUIZSERVICE
          predicates:
            - Path=/QUIZSERVICE/quiz/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        - id: question-service
          uri: lb://QUESTIONSERVICE
          predicates:
            - Path=/QUESTIONSERVICE/question/**
          filters:
            - StripPrefix=1
            - name: AuthenticationFilter

        - id: secure-microservices
          uri: lb://SECUREMICROSERVICES
          predicates:
            - Path=/auth/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
